<?php

// list of all sabre services http://andreypolyak.github.io/sabre-apis-ru/services.html

return [
	[
		'service'       => 'AirSeatCancelLLSRQ',
		'version'       => '2.1.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/cancel_air_seat/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/AirSeatCancelLLS2.1.0RQ.wsdl',
		'description'   => 'Удаление забронированных мест в салоне',
	],
	[
		'service'       => 'AirTicketLLSRQ',
		'version'       => '2.10.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/fulfill/issue_air_ticket/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/AirTicketLLS2.10.0RQ.wsdl',
		'description'   => 'Оформление билетов или EMD',
	],
	[
		'service'       => 'AirTicketRQ',
		'version'       => '1.1.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/fulfill/orchestrated_air_ticket/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/AirTicket1.1.0RQ.wsdl',
		'description'   => 'Оформление билетов или EMD',
	],
	[
		'service'       => 'AutomatedExchangesLLSRQ',
		'version'       => '2.6.1',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/fulfill/auto_price_air_exchanges/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/AutomatedExchangesLLS2.6.1RQ.wsdl',
		'description'   => 'Расчет стоимости обмена',
	],
	[
		'service'       => 'BargainFinderMax_ADRQ',
		'version'       => '3.2.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/bargain_finder_max/bfm_ad/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/shopping/BargainFinderMax_ADRQ_GIR_v3.2.0.wsdl',
		'description'   => 'Поиск перелетов по гибким датам',
	],
	[
		'service'       => 'BargainFinderMax_ASRQ',
		'version'       => '3.2.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/bargain_finder_max/alternate_airport_shop/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/shopping/BargainFinderMax_ASRQ_GIR_v3.2.0.wsdl',
		'description'   => 'Поиск перелетов по гибким направлениям',
	],
	[
		'service'       => 'BargainFinderMaxRQ',
		'version'       => '3.2.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/bargain_finder_max/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/shopping/BargainFinderMaxRQ_GIR_v3.2.0.wsdl',
		'description'   => 'Поиск перелетов',
	],
	[
		'service'       => 'ContextChangeLLSRQ',
		'version'       => '2.0.3',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/utility/change_aaa/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/ContextChangeLLS2.0.3RQ.wsdl',
		'description'   => 'Переход в другой PCC',
	],
	[
		'service'       => 'CreatePassengerNameRecordRQ',
		'version'       => '2.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/book/create_passenger_name_record/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/CreatePassengerNameRecord2.0.0RQ.wsdl',
		'description'   => 'Создание бронирования',
	],
	[
		'service'       => 'DeletePriceQuoteLLSRQ',
		'version'       => '2.1.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/book/delete_price_quote/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/DeletePriceQuoteLLS2.1.0RQ.wsdl',
		'description'   => 'Удаление PQ',
	],
	[
		'service'       => 'DeleteSpecialServiceLLSRQ',
		'version'       => '2.2.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/management/itinerary/delete_special_service/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/DeleteSpecialServiceLLS2.2.0RQ.wsdl',
		'description'   => 'Удаление специальных запросов',
	],
	[
		'service'       => 'DesignatePrinterLLSRQ',
		'version'       => '2.0.1',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/management/utility/designate_printer/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/DesignatePrinterLLS2.0.1RQ.wsdl',
		'description'   => 'Выбор принтера или стока',
	],
	[
		'service'       => 'DisplayCurrencyLLSRQ',
		'version'       => '2.1.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/utility/get_currency_conversion/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/DisplayCurrencyLLS2.1.0RQ.wsdl',
		'description'   => 'Получение курсов валют',
	],
	[
		'service'       => 'EndTransactionLLSRQ',
		'version'       => '2.0.7',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/itinerary/end_transaction/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/EndTransactionLLS2.0.7RQ.wsdl',
		'description'   => 'Сохранение бронирования',
	],
	[
		'service'       => 'EnhancedAirBookRQ',
		'version'       => '3.8.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/orchestrated_air_booking/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/EnhancedAirBook3.8.0RQ.wsdl',
		'description'   => 'Бронирование сегментов и расчет стоимости',
	],
	[
		'service'       => 'EnhancedSeatMapRQ',
		'version'       => '5.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/book/seat_map/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/Merchandising/EnhancedSeatMap_5_0_0.wsdl',
		'description'   => 'Получение карты мест',
	],
	[
		'service'       => 'eTicketCouponLLSRQ',
		'version'       => '2.0.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/fulfill/get_eticket_details/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/eTicketCouponLLS2.0.0RQ.wsdl',
		'description'   => 'Чтение маски билета или EMD',
	],
	[
		'service'       => 'eTicketRevalidateLLSRQ',
		'version'       => '2.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/fulfill/revalidate_eticket/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/eTicketRevalidateLLS2.0.0RQ.wsdl',
		'description'   => 'Ревалидация билетов',
	],
	[
		'service'       => 'ExchangeShoppingRQ',
		'version'       => '2.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/search/exchange_shopping/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/ExchangeShoppingRQ/2.0.0/ExchangeShopping2.0.0RQ.wsdl',
		'description'   => 'Поиск вариантов обмена',
	],
	[
		'service'       => 'GetAncillaryOffersRQ',
		'version'       => '3.0.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/get_ancillary_offers/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/Merchandising/GAO3/GetAncillaryOfferService_v3_00.wsdl',
		'description'   => 'Получение списка дополнительных услуг',
	],
	[
		'service'       => 'GetMarketingTextRQ',
		'version'       => '1.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/search/get_brand_marketing_text/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/sabreXML1.0.00/Merchandising/GetMarketingText.wsdl',
		'description'   => 'Получение информации о брендах перевозчика',
	],
	[
		'service'       => 'IgnoreTransactionLLSRQ',
		'version'       => '2.0.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/itinerary/ignore_transaction/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/IgnoreTransactionLLS2.0.0RQ.wsdl',
		'description'   => 'Игнорирование бронирования',
	],
	[
		'service'       => 'ModifyRemarkLLSRQ',
		'version'       => '2.1.2',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/management/itinerary/modify_itinerary_remark/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/ModifyRemarkLLS2.1.2RQ.wsdl',
		'description'   => 'Редактирование и удаление ремарок',
	],
	[
		'service'       => 'OTA_AirAvailLLSRQ',
		'version'       => '2.4.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/air_availability/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/OTA_AirAvailLLS2.4.0RQ.wsdl',
		'description'   => 'Получение информации о наличии мест',
	],
	[
		'service'       => 'OTA_AirPriceLLSRQ',
		'version'       => '2.16.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/price_air_itinerary/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/OTA_AirPriceLLS2.16.0RQ.wsdl',
		'description'   => 'Расчет стоимости',
	],
	[
		'service'       => 'OTA_AirRulesLLSRQ',
		'version'       => '2.2.1',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/air_fare_rules/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/OTA_AirRulesLLS2.2.1RQ.wsdl',
		'description'   => 'Получение текста правил тарифов',
	],
	[
		'service'       => 'OTA_AirScheduleLLSRQ',
		'version'       => '2.1.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/flight_schedules/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/OTA_AirScheduleLLS2.1.0RQ.wsdl',
		'description'   => 'Получения расписаний',
	],
	[
		'service'       => 'OTA_CancelLLSRQ',
		'version'       => '2.0.2',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/cancel_itinerary_segments/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/OTA_CancelLLS2.0.2RQ.wsdl',
		'description'   => 'Удаление сегментов',
	],
	[
		'service'       => 'OTA_PingRQ',
		'version'       => '1.0.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/session_management/refresh_session/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/OTA_PingRQ.wsdl',
		'description'   => 'Обновление сессии',
	],
	[
		'service'       => 'PassengerDetailsRQ',
		'version'       => '3.3.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/itinerary/Passenger_Details/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/ServicesPlatform/PassengerDetails3.3.0RQ.wsdl',
		'description'   => 'Добавление данных о пассажирах',
	],
	[
		'service'       => 'PO_AllBrandsPricingRQ',
		'version'       => '1.0.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/price_with_multiple_brands/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/SabreAir/PO_AllBrandsPricingRQ_v1.0.0.wsdl',
		'description'   => 'Расчет стоимости перелета по всем брендам',
	],
	[
		'service'       => 'PromotionalShoppingRQ',
		'version'       => '1.0.4',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/search/Shop_by_Specific_Fare/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/shopping/PromotionalRQ_v1-0-4.wsdl',
		'description'   => 'Поиск мест по коду тарифа',
	],
	[
		'service'       => 'QueueAccessLLSRQ',
		'version'       => '2.0.8',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/queue/access_queue/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/QueueAccessLLS2.0.8RQ.wsdl',
		'description'   => 'Управление очередями',
	],
	[
		'service'       => 'QueueCountLLSRQ',
		'version'       => '2.2.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/queue/get_queue_count/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/QueueCountLLS2.2.0RQ.wsdl',
		'description'   => 'Получение списка очередей',
	],
	[
		'service'       => 'QueuePlaceLLSRQ',
		'version'       => '2.0.4',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/queue/place_queue_message/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/QueuePlaceLLS2.0.4RQ.wsdl',
		'description'   => 'Постановка бронирования в очередь',
	],
	[
		'service'       => 'RulesFromPriceLLSRQ',
		'version'       => '2.1.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/air/book/fare_rules_from_air_price/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/RulesFromPriceLLS2.1.0RQ.wsdl',
		'description'   => 'Получения текста правил тарифов для текущего бронирования',
	],
	[
		'service'       => 'SabreCommandLLSRQ',
		'version'       => '1.8.1',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/management/utility/send_sabre_command/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/sabreXML1.0.00/tpf/SabreCommandLLS1.8.1RQ.wsdl',
		'description'   => 'Отправка терминальных команд',
	],
	[
		'service'       => 'SessionCloseRQ',
		'version'       => '1.0.1',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/session_management/close_session/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionCloseRQ.wsdl',
		'description'   => 'Закрытие сессии',
	],
	[
		'service'       => 'SessionCreateRQ',
		'version'       => '1.0.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/session_management/create_session/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/sabreXML1.0.00/usg/SessionCreateRQ.wsdl',
		'description'   => 'Создание сессии',
	],
	[
		'service'       => 'StructureFareRulesRQ',
		'version'       => '1.0.2',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/utility/get_structured_fare_rules/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/SabreAir/StructureFareRulesRQ_v1.0.2.wsdl',
		'description'   => 'Получение структурированных правил тарифов',
	],
	[
		'service'       => 'TKT_TravelAgencyReportsRQ',
		'version'       => '1.2.2',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/fulfill/display_audit_trail/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/fulfillment/TKT_AsrServices_v.1.2.2.wsdl',
		'description'   => 'Получение отчета о продажах',
	],
	[
		'service'       => 'TokenCreateRQ',
		'version'       => '1.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/session_management/create_access_token/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/usg/TokenCreateRQ.wsdl',
		'description'   => 'Создание токена доступа',
	],
	[
		'service'       => 'TravelItineraryDivideLLSRQ',
		'version'       => '2.0.2',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/itinerary/divide_itinerary/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/TravelItineraryDivideLLS2.0.2RQ.wsdl',
		'description'   => 'Деление бронирований',
	],
	[
		'service'       => 'TravelItineraryHistoryLLSRQ',
		'version'       => '2.3.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/management/itinerary/get_itinerary_history/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/TravelItineraryHistoryLLS2.3.0RQ.wsdl',
		'description'   => 'Чтение истории бронирования',
	],
	[
		'service'       => 'TravelItineraryModifyInfoLLSRQ',
		'version'       => '2.1.1',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/itinerary/modify_itinerary/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/TravelItineraryModifyInfoLLS2.1.1RQ.wsdl',
		'description'   => 'Редактирование бронирования',
	],
	[
		'service'       => 'TravelItineraryReadRQ',
		'version'       => '3.9.0',
		'documentation' => 'https://developer.sabre.com/docs/soap_apis/management/itinerary/get_itinerary/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/pnrservices/TravelItineraryReadRQ3.9.0.wsdl',
		'description'   => 'Чтение бронирования',
	],
	[
		'service'       => 'UnusedeTicketReportLLSRQ',
		'version'       => '2.0.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/fulfill/get_unused_etickets/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/UnusedeTicketReportLLS2.0.0RQ.wsdl',
		'description'   => 'Формирование отчета о неиспользованных билетах',
	],
	[
		'service'       => 'UpdateReservationRQ',
		'version'       => '1.16.0',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/management/itinerary/update_itinerary/resources',
		'wsdl'          => 'http://files.developer.sabre.com/wsdl/sabreXML1.0.00/pnrservices/UpdateReservation_1.16.0.wsdl',
		'description'   => 'Изменение бронирования',
	],
	[
		'service'       => 'VoidTicketLLSRQ',
		'version'       => '2.0.2',
		'documentation' => 'https://developer.sabre.com/docs/read/soap_apis/air/fulfill/Void_Air_Ticket/resources',
		'wsdl'          => 'http://webservices.sabre.com/wsdl/tpfc/VoidTicketLLS2.0.2RQ.wsdl',
		'description'   => 'Войдирование билетов или EMD',
	],
];